### ISSUE TITLE
The base URL isn't listed in your documentation

### ISSUE THREAD

**Issue by ParvenuDev** [Shroud-email/shroud.email#47]
I spent an hour searching for something that doesn't exist

**Comment by taobojlen** [comment]
Hi @ParvenuDev, can you please explain what you mean by base URL in this case? If you mean for self-hosting, the [documentation says](https://shroud.email/docs/deployment/self-host/#step-1-create-dns-records):

> Shroud.email uses two domains. If your domain is e.g. example.com, then the first domain (APP_DOMAIN in .env) is where the web UI will be served (e.g. app.example.com). The second domain (EMAIL_DOMAIN) is the domain used by email aliases.

**Comment by taobojlen** [comment]
I'm closing this as I'm not sure what you're looking for. Please feel free to reach out on hello@shroud.email for support.
